### ISSUE TITLE
Crash while trying to ride a horse

### ISSUE THREAD

**Issue by x-xLevix-x** [AlaharranHonor/SWDecoM#11]
I'm playing the 1.16.5 version, I only have the required mods installed and my game crashes 100% of the time while clicking a SWEM horse. Tried it 4 times.
Crash report and mod folder screenshot:
![Mod-folder-screen](https://github.com/AlaharranHonor/SWDecoM/assets/147777282/b536546b-e3d6-4970-90b8-ecae471190ea)

Description: Ticking entity

java.lang.NoSuchMethodError: software.bernie.geckolib3.core.manager.AnimationFactory.getOrCreateAnimationData(Ljava/lang/Integer;)Lsoftware/bernie/geckolib3/core/manager/AnimationData;
	at com.alaharranhonor.swem.client.animation.PlayerAnimationController.tick(PlayerAnimationController.java:52) ~[?:1.16.5-0.5.3.0] {re:mixin,re:classloading}
	at net.minecraft.client.entity.player.AbstractClientPlayerEntity.func_70071_h_(AbstractClientPlayerEntity.java:550) ~[?:?] {re:mixin,xf:fml:forge:bows.0,pl:runtimedistcleaner:A,re:classloading,xf:fml:forge:bows.0,pl:mixin:APP:swem.mixins.json:client.AbstractClientPlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70071_h_(ClientPlayerEntity.java:177) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:swem.mixins.json:client.ClientPlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:1611) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70098_U(LivingEntity.java:2578) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.player.PlayerEntity.func_70098_U(PlayerEntity.java:451) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:playerAnimator-common.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70098_U(ClientPlayerEntity.java:786) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:swem.mixins.json:client.ClientPlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217420_a(ClientWorld.java:214) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:199) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld$$Lambda$6746/1978456110.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:161) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1485) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:954) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$467/1832657711.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.alaharranhonor.swem.client.animation.PlayerAnimationController.tick(PlayerAnimationController.java:52) ~[?:1.16.5-0.5.3.0] {re:mixin,re:classloading}
	at net.minecraft.client.entity.player.AbstractClientPlayerEntity.func_70071_h_(AbstractClientPlayerEntity.java:550) ~[?:?] {re:mixin,xf:fml:forge:bows.0,pl:runtimedistcleaner:A,re:classloading,xf:fml:forge:bows.0,pl:mixin:APP:swem.mixins.json:client.AbstractClientPlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70071_h_(ClientPlayerEntity.java:177) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:swem.mixins.json:client.ClientPlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.entity.Entity.func_70098_U(Entity.java:1611) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.entity.LivingEntity.func_70098_U(LivingEntity.java:2578) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.entity.player.PlayerEntity.func_70098_U(PlayerEntity.java:451) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:playerAnimator-common.mixins.json:PlayerEntityMixin,pl:mixin:A}
	at net.minecraft.client.entity.player.ClientPlayerEntity.func_70098_U(ClientPlayerEntity.java:786) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:mixin:APP:swem.mixins.json:client.ClientPlayerEntityMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217420_a(ClientWorld.java:214) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld.func_217418_a(ClientWorld.java:199) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.world.ClientWorld$$Lambda$6746/1978456110.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: swem:swem_horse (com.alaharranhonor.swem.entities.SWEMHorseEntity)
	Entity ID: 69
	Entity Name: SWEM Horse
	Entity's Exact location: 46.87, 73.00, 130.98
	Entity's Block location: World: (46,73,130), Chunk: (at 14,4,2 in 2,8; contains blocks 32,0,128 to 47,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: 0.00, -0.03, 0.00
	Entity's Passengers: [ClientPlayerEntity['x_xLevix_x'/222, l='ClientLevel', x=44.60, y=74.00, z=130.74]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:161) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}

-- Affected level --
Details:
	All players: 1 total; [ClientPlayerEntity['x_xLevix_x'/222, l='ClientLevel', x=44.60, y=74.00, z=130.74]]
	Chunk stats: Client Chunk Cache: 1225, 862
	Level dimension: minecraft:overworld
	Level spawn location: World: (112,69,112), Chunk: (at 0,4,0 in 7,7; contains blocks 112,0,112 to 127,255,127), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 11173 game time, 11173 day time
	Server brand: forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.world.ClientWorld.func_72914_a(ClientWorld.java:447) ~[?:?] {re:mixin,pl:runtimedistcleaner:A,re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2031) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:623) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.2.34.jar:36.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$467/1832657711.call(Unknown Source) [forge-1.16.5-36.2.34.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 915208488 bytes (872 MB) / 2113929216 bytes (2016 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+IgnoreUnrecognizedVMOptions -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.34.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.34.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.34
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.34-client.jar                   |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.34-universal.jar                |Forge                         |forge                         |36.2.34             |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		geckolib-forge-1.16.5-3.0.100.jar                 |GeckoLib                      |geckolib3                     |3.0.100             |DONE      |Manifest: NOSIGNATURE
		swem-1.16.5-0.5.3.0.jar                           |Star Worm Equestrian Mod      |swem                          |1.16.5-0.5.3.0      |DONE      |Manifest: NOSIGNATURE
		player-animation-lib-forge-0.4.0-test0+1.16.5.jar |Player Animator               |playeranimator                |0.4.0-test0+1.16.5  |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 14ca875f-2e8b-4c8f-94c5-528122350fb3
	Launched Version: 1.16.5-forge-36.2.34
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics 630 GL version 4.6.0 - Build 27.20.100.8729, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz

**Comment by x-xLevix-x** [comment]
Posted it here because I get a 404 error on the SWEM bug report website...
